#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t devtmpfs none /dev
mount -t tmpfs none /tmp
chmod 777 / /tmp

# note: it may be useful to run a "heater" program here
# that warms up the QEMU JIT cache before starting the
# AFL fork server:
#
# /bin/heater /heaterfiles/*

exec DRIVER
